#ifndef _RAZE_HTTP_PROTOCOL_H
#define _RAZE_HTTP_PROTOCOL_H

enum raze_http_method {
	RAZE_HTTP_GET,
	RAZE_HTTP_HEAD,
	RAZE_HTTP_POST,
	RAZE_HTTP_PUT,
	RAZE_HTTP_DELETE,
	RAZE_HTTP_CONNECT,
	RAZE_HTTP_OPTIONS,
	RAZE_HTTP_TRACE
};

enum raze_http_version {
	RAZE_HTTP_0_9,
	RAZE_HTTP_1_0,
	RAZE_HTTP_1_1,
	RAZE_HTTP_2,
	RAZE_HTTP_3
};

enum raze_http_status_code {
	// 1xx: Informational
	RAZE_HTTP_CONTINUE = 100,
	RAZE_HTTP_SWITCH_PROTOCOL = 101,
	RAZE_HTTP_PROCESSING = 102,
	RAZE_HTTP_EARLY_HINTS = 103,

	// 2xx: Success
	RAZE_HTTP_OK = 200,
	RAZE_HTTP_CREATED = 201,
	RAZE_HTTP_ACCEPTED = 202,
	RAZE_HTTP_NON_AUTHORITATIVE_INFORMATION = 203,
	RAZE_HTTP_NO_CONTENT = 204,
	RAZE_HTTP_RESET_CONTENT = 205,
	RAZE_HTTP_PARTIAL_CONTENT = 206,

	// 3xx: Redirection
	RAZE_HTTP_MULTIPLE_CHOICES = 300,
	RAZE_HTTP_MOVED_PERMANENTLY = 301,
	RAZE_HTTP_FOUND = 302,
	RAZE_HTTP_SEE_OTHER = 303,
	RAZE_HTTP_NOT_MODIFIED = 304,
	RAZE_HTTP_TEMPORARY_REDIRECT = 307,
	RAZE_HTTP_PERMANENT_REDIRECT = 308,

	// 4xx: Client Error
	RAZE_HTTP_BAD_REQUEST = 400,
	RAZE_HTTP_UNAUTHORIZED = 401,
	RAZE_HTTP_PAYMENT_REQUIRED = 402,
	RAZE_HTTP_FORBIDDEN = 403,
	RAZE_HTTP_NOT_FOUND = 404,
	RAZE_HTTP_METHOD_NOT_ALLOWED = 405,
	RAZE_HTTP_NOT_ACCEPTABLE = 406,
	RAZE_HTTP_PROXY_AUTHENTICATION_REQUIRED = 407,
	RAZE_HTTP_REQUEST_TIMEOUT = 408,
	RAZE_HTTP_CONFLICT = 409,
	RAZE_HTTP_GONE = 410,
	RAZE_HTTP_LENGTH_REQUIRED = 411,
	RAZE_HTTP_PRECONDITION_FAILED = 412,
	RAZE_HTTP_PAYLOAD_TOO_LARGE = 413,
	RAZE_HTTP_URI_TOO_LONG = 414,
	RAZE_HTTP_UNSUPPORTED_MEDIA_TYPE = 415,
	RAZE_HTTP_RANGE_NOT_SATISFIABLE = 416,
	RAZE_HTTP_EXPECTATION_FAILED = 417,
	RAZE_HTTP_IM_A_TEAPOT = 418,
	RAZE_HTTP_UNPROCESSABLE_ENTITY = 422,
	RAZE_HTTP_TOO_MANY_REQUESTS = 429,

	// 5xx: Server Error
	RAZE_HTTP_INTERNAL_SERVER_ERROR = 500,
	RAZE_HTTP_NOT_IMPLEMENTED = 501,
	RAZE_HTTP_BAD_GATEWAY = 502,
	RAZE_HTTP_SERVICE_UNAVAILABLE = 503,
	RAZE_HTTP_GATEWAY_TIMEOUT = 504,
	RAZE_HTTP_HTTP_VERSION_NOT_SUPPORTED = 505
};

const char *raze_http_version_to_string(enum raze_http_version version);
const char *raze_http_status_code_to_string(enum raze_http_status_code status_code);

#endif
